### ISSUE TITLE
IE

### ISSUE THREAD

**Issue by bphilippus** [brandonaaron/jquery-spellcheck#1]
Doesn't seem to work in IE.

**Comment by joneschrisan** [comment]
Which version of IE does this not work on?

**Comment by bphilippus** [comment]
Sorry, that was over 2 years ago.  I've long since forgotten.

**Comment by joneschrisan** [comment]
Lol. Then I would probably say its working, I've tested in ie 8 and 9 and it seams to work but then I did make some enhancements / changes on my branch so that could have fixed the issue without me knowing if it doesn't work.
